In [15]:
import numpy as np

def getGaussianDisPro(varX, mu, sigma):
    '''
    :param varX: numpy.array
    :param mu: the mean value argument in Gaussian distribution, \
            and mu has the same shape as varX
    :param sigma: the co-variance matrix
    :return: the probability of varX in distribution
    '''
    _, n = np.mat(varX).shape
    A = np.power(2 * np.pi, n / 2.) * np.power( np.linalg.det(np.mat(sigma)), 0.5 )
    A = 1 / A
    B = np.exp( -0.5 * np.mat(varX - mu) * np.mat(sigma).I *
                np.mat(varX - mu).T )
    return A * B

x = np.array([[1,2],
              [1,1],
              [-1,2]])
mu = np.array([0,0])
sigma = np.eye(2)

np.apply_along_axis(getGaussianDisPro, 1, x, mu, sigma)

matrix([[ 0.01306423,  0.05854983,  0.01306423]])

In [17]:
print(getGaussianDisPro(np.array([1, 2]), mu, sigma))
print(getGaussianDisPro(np.array([1, 1]), mu, sigma))
getGaussianDisPro(np.array([-1, 2]), mu, sigma)

[[ 0.01306423]]
[[ 0.05854983]]


matrix([[ 0.01306423]])

In [43]:
aa = np.mat(np.random.randint(3, size=(3, 2)))
print(aa)

[[1 1]
 [1 0]
 [2 2]]
--------------------


In [49]:
np.sum(aa, axis=1)

matrix([[2],
        [1],
        [4]])

In [56]:
ab = np.random.rand(1, 5)
print(ab)

[[ 0.33275238  0.43995737  0.56611994  0.68943736  0.66477394]]


In [57]:
ab ** 2

array([[ 0.11072415,  0.19356249,  0.32049179,  0.47532388,  0.44192439]])

In [61]:
ab

array([[ 0.33275238,  0.43995737,  0.56611994,  0.68943736,  0.66477394]])

In [71]:
def f(x):
    return x+1

np.apply_along_axis(f, 0, [1.1, 1.2])

array([ 2.1,  2.2])

In [83]:
ma = np.mat(np.random.randint(10, size=(3,3)))
mb = np.mat(np.random.randint(10, size=(3,3)))
print(ma)
print(mb)

[[7 9 8]
 [4 7 1]
 [4 7 0]]
[[2 3 1]
 [6 2 6]
 [3 7 5]]


In [84]:
print(ma + mb)

[[ 9 12  9]
 [10  9  7]
 [ 7 14  5]]


In [87]:
np.add(ma, mb)

matrix([[ 9, 12,  9],
        [10,  9,  7],
        [ 7, 14,  5]])